
import clases.Conexion;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author The_S
 */
public class DetalleNotaVenta extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    private final DefaultTableModel tableModel = new DefaultTableModel();
    private double[][] data;
    DefaultTableModel model;
    protected boolean bottom = true;
    protected boolean top = true;

    public DetalleNotaVenta() {
        initComponents();
    }

    public PdfPCell getCell(String text, Font font, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(0);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    public static PdfPCell createImageCell(String path) throws DocumentException, IOException {
        Image img = Image.getInstance(path);
        PdfPCell cell = new PdfPCell(img, true);
        cell.setBorder(Rectangle.NO_BORDER);
        return cell;
    }

    public void tableLayout(PdfPTable table, float[][] width, float[] height,
            int headerRows, int rowStart, PdfContentByte[] canvas) {
        float widths[] = width[0];
        float y1 = height[0];
        float y2 = height[height.length - 1];
        float x1 = widths[0];
        float x2 = widths[widths.length - 1];
        PdfContentByte cb = canvas[PdfPTable.LINECANVAS];
        cb.moveTo(x1, y1);
        cb.lineTo(x1, y2);
        cb.moveTo(x2, y1);
        cb.lineTo(x2, y2);
        if (top) {
            cb.moveTo(x1, y1);
            cb.lineTo(x2, y1);
        }
        if (bottom) {
            cb.moveTo(x1, y2);
            cb.lineTo(x2, y2);
        }
        cb.stroke();
        cb.resetRGBColorStroke();
        bottom = true;
        top = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane4 = new javax.swing.JLayeredPane();
        jPanel33 = new javax.swing.JPanel();
        btnVolver4 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblProductosOrdenCompra = new javax.swing.JTable();
        txtDescripcionOC = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        txtEstadoOC = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        txtRutCompradorOC = new javax.swing.JTextField();
        txtDireccionDemandanteOC = new javax.swing.JTextField();
        txtTelefonoComprador = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        txtNombreDemandanteOC = new javax.swing.JTextField();
        txtUnidadCompraCliente = new javax.swing.JTextField();
        jLabel114 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        txtFechaEnvioOc = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        txtProveedorOC = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        txtNombreOrdenCompra = new javax.swing.JTextField();
        txtFechaEntregaProductoOC = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        txtDireccionesDespachoOC = new javax.swing.JTextField();
        txtDireccionEnvioFacturaOC = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        txtMailEnvioFactura = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        txtContactoOC = new javax.swing.JTextField();
        txtContactoPagoOC = new javax.swing.JTextField();
        txtFormaPagoOC = new javax.swing.JTextField();
        txtMetodoDespachoOC = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtCodigoOCOT = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        txtImpuestoEspecifico = new javax.swing.JTextField();
        txtIVAOC = new javax.swing.JTextField();
        txtSubtotalOC = new javax.swing.JTextField();
        txtCargosOC = new javax.swing.JTextField();
        txtDCTOOC = new javax.swing.JTextField();
        txtNetoOC = new javax.swing.JTextField();
        txtTotalOC = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        btnImprimirNotaVenta = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        lblCodigoOCTitulo = new javax.swing.JLabel();
        txtConsultarOC = new javax.swing.JTextField();
        btnConsultarOC = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblFondoOrdenTrabajo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane4.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLayeredPane4.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new Color(0, 0, 0, 0));
        jPanel33.setBackground(new java.awt.Color(0, 153, 153));

        btnVolver4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnVolver4.setText("Volver");
        btnVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver4ActionPerformed(evt);
            }
        });

        jTabbedPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel93.setText("Información de la empresa:");

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel102.setText("Información del Demandante:");

        jLabel103.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel103.setText("Información de Nota de Venta:");

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel113.setText("Detalle de Nota:");

        tblProductosOrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", null}
            },
            new String [] {
                "Código de Producto", "Producto", "Cantidad", "Especificación de Comprador", "Especificación de Proveedor", "Moneda", "Precio Unitario", "Cargos", "Descuento", "Valor Total"
            }
        ));
        jScrollPane13.setViewportView(tblProductosOrdenCompra);

        jTabbedPane9.addTab("Información de Productos", jScrollPane13);

        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel100.setText("Estado:");

        jLabel101.setText("Teléfono:");

        jLabel97.setText("Dirección Demandante:");

        jLabel96.setText("Rut de Comprador:");

        jLabel98.setText("Demandante:");

        jLabel114.setText("Unidad de Compra:");

        jLabel99.setText("Fecha de Envio OC:");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel100)
                    .addComponent(jLabel97)
                    .addComponent(jLabel101)
                    .addComponent(jLabel96))
                .addGap(10, 10, 10)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoComprador, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtDireccionDemandanteOC)
                    .addComponent(txtRutCompradorOC)
                    .addComponent(txtEstadoOC))
                .addGap(39, 39, 39)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel99)
                    .addComponent(jLabel98)
                    .addComponent(jLabel114))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUnidadCompraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(txtFechaEnvioOc)
                    .addComponent(txtNombreDemandanteOC))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel98)
                    .addComponent(txtNombreDemandanteOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel96)
                    .addComponent(txtRutCompradorOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(txtUnidadCompraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel97)
                    .addComponent(txtDireccionDemandanteOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel99)
                    .addComponent(txtFechaEnvioOc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel101)
                    .addComponent(txtTelefonoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel100))
                .addContainerGap())
        );

        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel90.setText("Proveedor:");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProveedorOC, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProveedorOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel90))
                .addContainerGap())
        );

        jPanel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel104.setText("Nombre de Orden de Compra:");

        txtNombreOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreOrdenCompraActionPerformed(evt);
            }
        });

        jLabel105.setText("Fecha de Aceptación:");

        jLabel106.setText("Direcciones de Despacho:");

        txtDireccionesDespachoOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionesDespachoOCActionPerformed(evt);
            }
        });

        txtDireccionEnvioFacturaOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEnvioFacturaOCActionPerformed(evt);
            }
        });

        jLabel107.setText("Dirección de Envío de factura:");

        jLabel112.setText("Mail de envío de factura:");

        jLabel108.setText("Metodo de Despacho:");

        jLabel110.setText("Forma de Pago:");

        jLabel109.setText("Contacto de Pago:");

        jLabel111.setText("Contacto OC:");

        jLabel42.setText("Código de Orden de Compra:");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel107)
                    .addComponent(jLabel112)
                    .addComponent(jLabel106)
                    .addComponent(jLabel105)
                    .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDireccionEnvioFacturaOC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtDireccionesDespachoOC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaEntregaProductoOC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreOrdenCompra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMailEnvioFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel110)
                            .addComponent(jLabel108)
                            .addComponent(jLabel109)
                            .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFormaPagoOC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(txtContactoPagoOC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContactoOC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMetodoDespachoOC))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel37Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoOCOT)))
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel104)
                    .addComponent(txtNombreOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel108)
                    .addComponent(txtMetodoDespachoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaEntregaProductoOC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel105)
                        .addComponent(txtFormaPagoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel110)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionesDespachoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109)
                    .addComponent(txtContactoPagoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel106))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel107)
                    .addComponent(txtDireccionEnvioFacturaOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111)
                    .addComponent(txtContactoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMailEnvioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112)
                    .addComponent(jLabel42)
                    .addComponent(txtCodigoOCOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel115.setText("Neto:");

        jLabel116.setText("Dcto:");

        jLabel117.setText("Cargos:");

        jLabel118.setText("Subtotal:");

        jLabel119.setText("19% IVA:");

        jLabel120.setText("Impuesto Especifico:");

        jLabel121.setText("Total:");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel118)
                    .addComponent(jLabel117)
                    .addComponent(jLabel116)
                    .addComponent(jLabel115))
                .addGap(59, 59, 59)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCargosOC)
                    .addComponent(txtSubtotalOC)
                    .addComponent(txtDCTOOC)
                    .addComponent(txtNetoOC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel121)
                    .addComponent(jLabel119)
                    .addComponent(jLabel120))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtImpuestoEspecifico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtTotalOC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIVAOC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel115)
                    .addComponent(txtNetoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addComponent(jLabel119)
                    .addComponent(txtIVAOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel116)
                    .addComponent(txtDCTOOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel120)
                    .addComponent(txtImpuestoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel117)
                    .addComponent(txtCargosOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121)
                    .addComponent(txtTotalOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel118)
                    .addComponent(txtSubtotalOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImprimirNotaVenta.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnImprimirNotaVenta.setText("Imprimir Nota de Venta");
        btnImprimirNotaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirNotaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addComponent(jLabel113)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcionOC))
                            .addComponent(jTabbedPane9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103)
                            .addComponent(jLabel102)
                            .addComponent(jLabel93)
                            .addComponent(btnImprimirNotaVenta))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnImprimirNotaVenta)
                .addContainerGap())
        );

        jPanel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCodigoOCTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCodigoOCTitulo.setText("Número de Nota de Venta:");

        txtConsultarOC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtConsultarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarOCActionPerformed(evt);
            }
        });

        btnConsultarOC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnConsultarOC.setText("Consultar");
        btnConsultarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarOCActionPerformed(evt);
            }
        });

        lblCodigo.setVisible(false);

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCodigo))
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCodigoOCTitulo)
                        .addGap(4, 4, 4)
                        .addComponent(txtConsultarOC, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarOC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCodigoOCTitulo)
                    .addComponent(txtConsultarOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarOC))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel12);

        jTabbedPane3.addTab("Detalle de Nota de Venta", jScrollPane7);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver4)
                .addContainerGap())
            .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel33Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver4)
                .addContainerGap(643, Short.MAX_VALUE))
            .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLayeredPane4.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 690));

        lblFondoOrdenTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondoOrdenTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuTest.png"))); // NOI18N
        jLayeredPane4.add(lblFondoOrdenTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver4ActionPerformed

    private void txtNombreOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreOrdenCompraActionPerformed

    }//GEN-LAST:event_txtNombreOrdenCompraActionPerformed

    private void txtDireccionesDespachoOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionesDespachoOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionesDespachoOCActionPerformed

    private void txtDireccionEnvioFacturaOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEnvioFacturaOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEnvioFacturaOCActionPerformed

    private void txtConsultarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultarOCActionPerformed

    private void btnConsultarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarOCActionPerformed
        try {
            String tipoOrden = "";
            //JOptionPane.showMessageDialog(null, "La Orden de Compra se encuentra en la base de datos");
            //Consulta de BD
            String query = "SELECT * FROM acimabasededatos.ordenTrabajo oc where oc.codigoOrdenCompra=?;";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, txtConsultarOC.getText());
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                txtProveedorOC.setText(rs.getString("nombre_proveedor"));
                txtRutCompradorOC.setText(rs.getString("rutCliente"));
                txtDireccionDemandanteOC.setText(rs.getString("direcciondemandante"));
                txtTelefonoComprador.setText(rs.getString("telefono"));
                txtNombreDemandanteOC.setText(rs.getString("demandante"));
                txtUnidadCompraCliente.setText(rs.getString("unidadcompra"));
                txtFechaEnvioOc.setText(rs.getString("fechaenviooc"));
                txtEstadoOC.setText(rs.getString("codigoestado"));
                txtCodigoOCOT.setText(rs.getString("codigoordencompra"));
                txtNombreOrdenCompra.setText(rs.getString("nombreordencompra"));
                txtFechaEntregaProductoOC.setText(rs.getString("fechaaceptacion"));
                txtDireccionesDespachoOC.setText(rs.getString("direccionesdespacho"));
                txtDireccionEnvioFacturaOC.setText(rs.getString("direccionEnvioFactura"));
                txtMetodoDespachoOC.setText(rs.getString("tipoDespacho"));
                txtContactoPagoOC.setText(rs.getString("contactoPago"));
                txtFormaPagoOC.setText(rs.getString("formaPago"));
                txtContactoOC.setText(rs.getString("contactoOC"));
                txtMailEnvioFactura.setText(rs.getString("emailEnvioFactura"));
                txtCargosOC.setText(rs.getString("cargos"));
                txtNetoOC.setText(rs.getString("neto"));
                txtDCTOOC.setText(rs.getString("dcto"));
                txtSubtotalOC.setText(rs.getString("subtotal"));
                txtIVAOC.setText(rs.getString("iva"));
                txtImpuestoEspecifico.setText(rs.getString("impuestoEspecifico"));
                txtTotalOC.setText(rs.getString("total"));
            }
            String queryProducto = "Select doc.codigoProducto as 'Código de Producto',\n"
                    + "SUBSTRING_INDEX(doc.nombreProducto, ')', -1) as 'Nombre de Producto',doc.cantidad as 'Cantidad',\n"
                    + "oc.especificacionComprador as 'Especificación de Comprador',oc.especificacionProveedor as 'Especificación de Proveedor',\n"
                    + "oc.moneda,doc.precioUnitario as 'Precio Unitario', doc.descuento as 'Descuento',\n"
                    + "doc.cargos as 'Cargos', doc.valorTotal as 'Valor Total' from detalleordentrabajo doc\n"
                    + "join ordentrabajo oc on doc.codigoordencompra = oc.codigoordencompra\n"
                    + "where oc.codigoOrdenCompra=?;";
            PreparedStatement pstProd = cn.prepareStatement(queryProducto);
            pstProd.setString(1, txtConsultarOC.getText());
            ResultSet rsProd = pstProd.executeQuery();
            tblProductosOrdenCompra.setModel(DbUtils.resultSetToTableModel(rsProd));
            System.out.println("La consulta fue realizada con éxito");

            for (int i = 0; i < tblProductosOrdenCompra.getRowCount(); i++) {
                if (tblProductosOrdenCompra.getValueAt(i, 0) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 0);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 1) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 1);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 2) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 2);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 3) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 3);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 4) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 4);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 5) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 5);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 6) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 6);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 7) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 7);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 8) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 8);
                }
                if (tblProductosOrdenCompra.getValueAt(i, 9) == null) {
                    tblProductosOrdenCompra.setValueAt("N/A", i, 9);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarOCActionPerformed

    private void btnImprimirNotaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirNotaVentaActionPerformed

        int idCot = 0;
        String ruta = "";

        JFileChooser dlg = new JFileChooser();
        dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int option = dlg.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            ruta = f.toString();
        }

        //Fecha
        Date sistFecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd-MMM-YYYY");
        //Crear PDF
        try {
            Document doc = new Document(PageSize.A4);
            Date sistHora = new Date();
            String pmAm = "hh:mm a";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            Calendar hoy = Calendar.getInstance();
            String hora = (String.format(format.format(sistHora), hoy));
            hora = hora.replace(":", "-");
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(ruta + "\\" + "Detalle_de_nota_venta_" + txtConsultarOC.getText() + "_Fecha_" + formato.format(sistFecha) + "_hora_" + hora + ".pdf"));
            doc.open();
            //Añadir la imagen
            try {
                Image logoAcima = Image.getInstance("src\\Imagenes\\acima-logo-400p.png");
                logoAcima.scaleAbsolute(210, 112);
                doc.add(logoAcima);
                Paragraph separacion0 = new Paragraph("_______________________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
                doc.add(separacion0);
                Paragraph nro = new Paragraph("Número de Nota de Venta: " + txtConsultarOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
                nro.setAlignment(Paragraph.ALIGN_RIGHT);
                doc.add(nro);
                Paragraph separacion01 = new Paragraph("_______________________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
                doc.add(separacion01);

            } catch (BadElementException | IOException ex) {
                Logger.getLogger(DetalleNotaVenta.class
                        .getName()).log(Level.SEVERE, null, ex);

            }

            PdfPTable tableDatos = new PdfPTable(2);
            tableDatos.setWidthPercentage(100);
            tableDatos.addCell(new Phrase("Rut de Compradorl: " + txtRutCompradorOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Demandante: " + txtNombreDemandanteOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Dirección del Demandante: " + txtDireccionDemandanteOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Unidad de Compra: " + txtUnidadCompraCliente.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Telefono: " + txtTelefonoComprador.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Fecha de Envío de OC: " + txtFechaEnvioOc.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.addCell(new Phrase("Estado: " + txtEstadoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos.setSpacingBefore(15f);
            tableDatos.setWidthPercentage(100);
            Paragraph alineaDatos = new Paragraph();
            alineaDatos.add(tableDatos);
            doc.add(alineaDatos);

            PdfPTable tableDatos2 = new PdfPTable(2);
            tableDatos2.setWidthPercentage(100);
            tableDatos2.addCell(new Phrase("Proveedor: ", FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos2.addCell(new Phrase(txtRutCompradorOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));

            tableDatos2.setSpacingBefore(15f);
            tableDatos2.setWidthPercentage(100);
            Paragraph alineaDatos2 = new Paragraph();
            alineaDatos2.add(tableDatos2);
            doc.add(alineaDatos2);

            PdfPTable tableDatos3 = new PdfPTable(2);
            tableDatos3.setWidthPercentage(100);
            tableDatos3.addCell(new Phrase("Nombre de Orden de Compra: " + txtNombreOrdenCompra.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Metodo de Despacho: " + txtMetodoDespachoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Fecha de Aceptación: " + txtFechaEntregaProductoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Forma de Pago: " + txtFormaPagoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Dirección de despacho: " + txtDireccionesDespachoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Contacto de Pago: " + txtContactoPagoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Dirección de envío de factura: " + txtDireccionEnvioFacturaOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Contacto OC: " + txtContactoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Mail de envío de factura: " + txtMailEnvioFactura.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));
            tableDatos3.addCell(new Phrase("Código de orden de compra: " + txtCodigoOCOT.getText(), FontFactory.getFont(FontFactory.TIMES, 12)));

            tableDatos3.setSpacingBefore(15f);
            tableDatos3.setWidthPercentage(100);
            Paragraph alineaDatos3 = new Paragraph();
            alineaDatos3.add(tableDatos3);
            doc.add(alineaDatos3);

            Paragraph separacion2 = new Paragraph("_______________________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            doc.add(separacion2);
            Paragraph tablas = new Paragraph("Información de Cotizacion ", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(tablas);
            try {
                PdfPTable pdfTable = new PdfPTable(tblProductosOrdenCompra.getColumnCount());
                //Parámetros de espaciado y ancho
                pdfTable.setSpacingBefore(15f);
                pdfTable.setWidthPercentage(100);
                //Añadir Valores
                for (int i = 0; i < tblProductosOrdenCompra.getColumnCount(); i++) {
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getColumnName(i), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                }
                //Extraer valores de la Jtable al PDF
                for (int rows = 0; rows < tblProductosOrdenCompra.getRowCount(); rows++) {
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 0).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 1).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 2).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 3).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 4).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 5).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 6).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 7).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 8).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    pdfTable.addCell(new Phrase(tblProductosOrdenCompra.getModel().getValueAt(rows, 9).toString(), FontFactory.getFont(FontFactory.HELVETICA, 8)));

                }
                doc.add(pdfTable);
            } catch (DocumentException ex) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error: tabla" + ex.getMessage());
            }

            Paragraph neto = new Paragraph("Neto: " + txtNetoOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            neto.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph iva = new Paragraph("IVA: " + txtIVAOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            iva.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph dcto = new Paragraph("Descuento: " + txtDCTOOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            dcto.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph impuesto = new Paragraph("Impuesto Específico: " + txtImpuestoEspecifico.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            impuesto.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph cargos = new Paragraph("Cargos: " + txtCargosOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            cargos.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph total = new Paragraph("Total: " + txtTotalOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            total.setAlignment(Paragraph.ALIGN_RIGHT);
            Paragraph subtotal = new Paragraph("Subtotal: " + txtSubtotalOC.getText(), FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            subtotal.setAlignment(Paragraph.ALIGN_RIGHT);
            doc.add(neto);
            doc.add(iva);
            doc.add(dcto);
            doc.add(cargos);
            doc.add(impuesto);
            doc.add(total);
            doc.add(subtotal);
            Paragraph nota = new Paragraph("Esta cotización debe ser respondida dentro de 15 días hábiles", FontFactory.getFont(FontFactory.TIMES, 12, Font.NORMAL, null));
            doc.add(nota);
            Paragraph separacion3 = new Paragraph("_______________________________________________________________________________________", FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, null));
            separacion3.setSpacingBefore(15f);
            separacion3.setSpacingBefore(15f);
            doc.add(separacion3);
            //Iconos
            try {
                PdfPTable table = new PdfPTable(2);
                table.setWidths(new int[]{1, 12});
                table.getDefaultCell().setBorder(Rectangle.NO_BORDER);
                Image img1 = Image.getInstance("src\\Imagenes\\phone-icon-11-64.png");
                Image img2 = Image.getInstance("src\\Imagenes\\mail-64.png");
                table.addCell(new PdfPCell(img1, true));
                table.addCell(new Phrase("Central telefónica: +56-232 107 900", FontFactory.getFont(FontFactory.TIMES, 12)));
                table.addCell(new PdfPCell(img2, true));
                table.addCell(new Phrase("ventas@acima.cl - comercial@acima.cl - gerencia@acima.cl", FontFactory.getFont(FontFactory.TIMES, 12)));
                Paragraph tableFooter = new Paragraph();
                tableFooter.add(table);
                tableFooter.setSpacingBefore(15f);
                tableFooter.setSpacingBefore(15f);
                tableFooter.setAlignment(Paragraph.ALIGN_RIGHT);
                doc.add(tableFooter);
                doc.close();
                JOptionPane.showMessageDialog(null, "PDF Generado Correctamente");

            } catch (BadElementException | IOException ex) {
                Logger.getLogger(DetalleNotaVenta.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: sss" + ex.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DetalleNotaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnImprimirNotaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleNotaVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleNotaVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleNotaVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleNotaVenta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleNotaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarOC;
    private javax.swing.JButton btnImprimirNotaVenta;
    private javax.swing.JButton btnVolver4;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane9;
    public javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoOCTitulo;
    private javax.swing.JLabel lblFondoOrdenTrabajo;
    private javax.swing.JTable tblProductosOrdenCompra;
    private javax.swing.JTextField txtCargosOC;
    private javax.swing.JTextField txtCodigoOCOT;
    public javax.swing.JTextField txtConsultarOC;
    private javax.swing.JTextField txtContactoOC;
    private javax.swing.JTextField txtContactoPagoOC;
    private javax.swing.JTextField txtDCTOOC;
    private javax.swing.JTextField txtDescripcionOC;
    private javax.swing.JTextField txtDireccionDemandanteOC;
    private javax.swing.JTextField txtDireccionEnvioFacturaOC;
    private javax.swing.JTextField txtDireccionesDespachoOC;
    private javax.swing.JTextField txtEstadoOC;
    private javax.swing.JTextField txtFechaEntregaProductoOC;
    private javax.swing.JTextField txtFechaEnvioOc;
    private javax.swing.JTextField txtFormaPagoOC;
    private javax.swing.JTextField txtIVAOC;
    private javax.swing.JTextField txtImpuestoEspecifico;
    private javax.swing.JTextField txtMailEnvioFactura;
    private javax.swing.JTextField txtMetodoDespachoOC;
    private javax.swing.JTextField txtNetoOC;
    private javax.swing.JTextField txtNombreDemandanteOC;
    private javax.swing.JTextField txtNombreOrdenCompra;
    private javax.swing.JTextField txtProveedorOC;
    private javax.swing.JTextField txtRutCompradorOC;
    private javax.swing.JTextField txtSubtotalOC;
    private javax.swing.JTextField txtTelefonoComprador;
    private javax.swing.JTextField txtTotalOC;
    private javax.swing.JTextField txtUnidadCompraCliente;
    // End of variables declaration//GEN-END:variables
}
