
import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author The_S
 */
public class IngresoFactura extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public IngresoFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelFactura1 = new javax.swing.JScrollPane();
        panelMercaderia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNumeroNotaCompra = new javax.swing.JTextField();
        txtNumeroFactura = new javax.swing.JTextField();
        txtNumeroCotizacion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtRutEmpresa = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtGiroEmpresa = new javax.swing.JTextField();
        txtDireccionEmpresa = new javax.swing.JTextField();
        txtCorreoEmpresa = new javax.swing.JTextField();
        txtContactoEmpresa = new javax.swing.JTextField();
        txtTipoVenta = new javax.swing.JTextField();
        txtOrganizacion = new javax.swing.JTextField();
        txtRutCliente = new javax.swing.JFormattedTextField();
        txtGiroCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        cmbComunaMercaderia = new javax.swing.JComboBox<>();
        cmbRegionMercaderia = new javax.swing.JComboBox<>();
        txtContactoCliente = new javax.swing.JTextField();
        txtTipoCompra = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        txtPagos = new javax.swing.JTextField();
        txtFormaPago = new javax.swing.JTextField();
        txtMontoNeto = new javax.swing.JTextField();
        txtIvaDebito = new javax.swing.JTextField();
        txtImpuestoAdicional = new javax.swing.JTextField();
        txtExtento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnInsertarMercaderia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbEmpresaMercaderia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMercaderia = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        btnAgregarProductoMercaderia = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Salir");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        panelFactura1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        panelFactura1.setToolTipText("");
        panelFactura1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelMercaderia.setBackground(new java.awt.Color(252, 252, 252));

        jLabel1.setText("Número de Nota de Compra:");

        jLabel2.setText("Número de Factura:");

        jLabel3.setText("Número de Nota de Compra:");

        jLabel4.setText("Rut de Empresa:");

        jLabel5.setText("Giro de Empresa:");

        jLabel6.setText("Dirección de Empresa:");

        jLabel7.setText("Correo de Empresa:");

        jLabel8.setText("Contacto de Empresa:");

        jLabel9.setText("Tipo de Venta:");

        jLabel10.setText("Organización:");

        jLabel11.setText("Rut de Cliente:");

        jLabel12.setText("Giro de Cliente:");

        jLabel13.setText("Dirección de Cliente:");

        jLabel14.setText("Comuna de Cliente:");

        jLabel15.setText("Región de Cliente:");

        jLabel16.setText("Contacto de Cliente:");

        jLabel17.setText("Tipo de Compra:");

        jLabel22.setText("Referencias:");

        jLabel23.setText("Pagos:");

        jLabel24.setText("Forma de Pago:");

        jLabel25.setText("Monto Neto:");

        jLabel26.setText("Iva débito:");

        jLabel27.setText("Impuesto Adicional:");

        jLabel28.setText("Extento:");

        jLabel29.setText("Total:");

        try {
            txtRutEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtRutCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRutCliente.setText(".   .   - ");

        cmbComunaMercaderia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Comuna" }));

        cmbRegionMercaderia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Región" }));
        cmbRegionMercaderia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRegionMercaderiaItemStateChanged(evt);
            }
        });

        btnInsertarMercaderia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInsertarMercaderia.setText("Ingresar");
        btnInsertarMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarMercaderiaActionPerformed(evt);
            }
        });

        cmbEmpresaMercaderia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empresa", "Acima Global SPA", "Acima Soluciones Integrales SPA", "Miancafs Consultores SPA" }));
        cmbEmpresaMercaderia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEmpresaMercaderiaItemStateChanged(evt);
            }
        });

        tblMercaderia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        tblMercaderia.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMercaderia);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Productos");

        btnAgregarProductoMercaderia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarProductoMercaderia.setText("Agregar Producto a la lista");
        btnAgregarProductoMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoMercaderiaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Factura de Mercadería");

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMercaderiaLayout = new javax.swing.GroupLayout(panelMercaderia);
        panelMercaderia.setLayout(panelMercaderiaLayout);
        panelMercaderiaLayout.setHorizontalGroup(
            panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercaderiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(btnInsertarMercaderia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMercaderiaLayout.createSequentialGroup()
                        .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                            .addComponent(txtNumeroNotaCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumeroCotizacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRutEmpresa)
                            .addComponent(txtGiroEmpresa)
                            .addComponent(txtDireccionEmpresa)
                            .addComponent(txtCorreoEmpresa)
                            .addComponent(txtContactoEmpresa)
                            .addComponent(txtTipoVenta)
                            .addComponent(txtOrganizacion)
                            .addComponent(txtRutCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGiroCliente)
                            .addComponent(txtDireccionCliente)
                            .addComponent(cmbComunaMercaderia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRegionMercaderia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContactoCliente)
                            .addComponent(txtTipoCompra)
                            .addComponent(txtReferencia)
                            .addComponent(txtPagos)
                            .addComponent(txtFormaPago)
                            .addComponent(txtMontoNeto)
                            .addComponent(txtIvaDebito)
                            .addComponent(txtImpuestoAdicional)
                            .addComponent(txtExtento)
                            .addComponent(txtTotal)
                            .addComponent(cmbEmpresaMercaderia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMercaderiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarProductoMercaderia)))
                .addGap(10, 10, 10))
        );
        panelMercaderiaLayout.setVerticalGroup(
            panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercaderiaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroNotaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEmpresaMercaderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRutEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtContactoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtGiroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbComunaMercaderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbRegionMercaderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProductoMercaderia)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtMontoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtIvaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtImpuestoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtExtento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertarMercaderia)
                .addContainerGap())
        );

        panelFactura1.setViewportView(panelMercaderia);

        jTabbedPane1.addTab("Factura de Mercadería", panelFactura1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cmbRegionMercaderiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRegionMercaderiaItemStateChanged
        String region = cmbRegionMercaderia.getSelectedItem().toString();

        if (region.equals("Seleccione Región")) {
            cmbComunaMercaderia.disable();
        } else {
            cmbComunaMercaderia.removeAllItems();
            cmbComunaMercaderia.enable();

            try {
                String query = "select co.nombreComuna "
                        + "from Comuna co join Region re on co.IDRegion = re.IDRegion "
                        + "where re.NombreRegion = ?  "
                        + "order by co.nombreComuna asc";
                String param = region;
                PreparedStatement pst = cn.prepareStatement(query);
                pst.setString(1, param);
                ResultSet rs = pst.executeQuery();
                cmbComunaMercaderia.addItem("Todas las Comunas");
                while (rs.next()) {
                    cmbComunaMercaderia.addItem(rs.getString(1));
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmbRegionMercaderiaItemStateChanged

    private void btnInsertarMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarMercaderiaActionPerformed
        try {
            int reply;
            do {
                reply = JOptionPane.showConfirmDialog(null, "Confirma Factura", null, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    String query = "INSERT INTO factura_compra_m (\n"
                            + "idCotizacion,numeroFacturaCompra_m,idOrden,rutEmpresa,giroEmpresa,direccionEmpresa,correoEmpresa,\n"
                            + "contactoEmpresa,tipoVenta,rutCliente,giroCliente,direccionCliente,idComuna,idRegion,\n"
                            + "contactoCliente,tipoCompra,referencias,pagos,formaPago,\n"
                            + "montoNeto,iva_debito,impuestoAdicional,extento,total )\n"
                            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
                    PreparedStatement insert = cn.prepareStatement(query);

                    insert.setString(1, txtNumeroCotizacion.getText());
                    insert.setString(2, txtNumeroFactura.getText());
                    insert.setString(3, txtNumeroNotaCompra.getText());
                    insert.setString(4, txtRutEmpresa.getText());
                    insert.setString(5, txtGiroEmpresa.getText());
                    insert.setString(6, txtDireccionEmpresa.getText());
                    insert.setString(7, txtCorreoEmpresa.getText());
                    insert.setString(8, txtContactoEmpresa.getText());
                    insert.setString(9, txtTipoVenta.getText());
                    insert.setString(10, txtRutCliente.getText());
                    insert.setString(11, txtGiroCliente.getText());
                    insert.setString(12, txtDireccionCliente.getText());
                    insert.setInt(13, cmbComunaMercaderia.getSelectedIndex());
                    insert.setInt(14, cmbRegionMercaderia.getSelectedIndex());
                    insert.setString(15, txtContactoCliente.getText());
                    insert.setString(16, txtTipoCompra.getText());
                    insert.setString(17, txtReferencia.getText());
                    insert.setString(18, txtPagos.getText());
                    insert.setString(19, txtFormaPago.getText());
                    insert.setString(20, txtMontoNeto.getText());
                    insert.setString(21, txtIvaDebito.getText());
                    insert.setString(22, txtImpuestoAdicional.getText());
                    insert.setString(23, txtExtento.getText());
                    insert.setString(24, txtTotal.getText());

                    int i = insert.executeUpdate();

                    int id = 0;
                    String query1 = "SELECT \n"
                            + "    CASE\n"
                            + "        WHEN IDfactura_compra_m IS NULL THEN '1'\n"
                            + "        ELSE max(IDfactura_compra_m)\n"
                            + "    END \n"
                            + "FROM\n"
                            + "    factura_compra_m;";
                    PreparedStatement pst1 = cn.prepareStatement(query1);
                    ResultSet rs1 = pst1.executeQuery();
                    while (rs1.next()) {
                        id = rs1.getInt(1);
                    }

                    int rowCount = tblMercaderia.getRowCount();
                    for (int x = 0; x < rowCount; x++) {
                        String queryProductos = "INSERT INTO detalle_factura_m (idFactura,nombreProducto,cantidad,precio,total )\n"
                                + "VALUES (?,?,?,?,?);";
                        PreparedStatement insertProductos = cn.prepareStatement(queryProductos);

                        insertProductos.setInt(1, id);
                        insertProductos.setString(2, tblMercaderia.getValueAt(x, 0).toString());
                        insertProductos.setString(3, tblMercaderia.getValueAt(x, 1).toString());
                        insertProductos.setString(4, tblMercaderia.getValueAt(x, 2).toString());
                        insertProductos.setString(5, tblMercaderia.getValueAt(x, 3).toString());

                        int r = insertProductos.executeUpdate();
                    }
                    JOptionPane.showMessageDialog(null, "Factura Ingresada");

                } else {
                    JOptionPane.showMessageDialog(null, "Modifique los datos antes de ingresar");
                }

            } while (reply == JOptionPane.NO_OPTION);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_btnInsertarMercaderiaActionPerformed

    private void cmbEmpresaMercaderiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEmpresaMercaderiaItemStateChanged
        if (cmbEmpresaMercaderia.getSelectedIndex() == 0) {
            txtRutEmpresa.setText("");
            txtGiroEmpresa.setText("");
            txtCorreoEmpresa.setText("");
            txtDireccionEmpresa.setText("");
            txtContactoEmpresa.setText("");
        } else if (cmbEmpresaMercaderia.getSelectedIndex() == 1) {
            txtRutEmpresa.setText("76.426.454-1");
            txtGiroEmpresa.setText("Acima Global SPA");
            txtCorreoEmpresa.setText("gerencia@acima.cl");
            txtDireccionEmpresa.setText("Av. 5 de abril 4454, Oficina 31, Estación Central, Santiago, Chile");
            txtContactoEmpresa.setText("+56-232107900");
        } else if (cmbEmpresaMercaderia.getSelectedIndex() == 2) {
            txtRutEmpresa.setText("76.473.504-8");
            txtGiroEmpresa.setText("Acima Soluciones Integrales SPA");
            txtDireccionEmpresa.setText("Av. 5 de abril 4454, Oficina 31, Estación Central, Santiago, Chile");
            txtCorreoEmpresa.setText("gerencia@acima.cl");
            txtContactoEmpresa.setText("+56-232107900");
        } else if (cmbEmpresaMercaderia.getSelectedIndex() == 3) {
            txtRutEmpresa.setText("");
            txtGiroEmpresa.setText("Miancafs Consultores SPA");
            txtDireccionEmpresa.setText("Av. 5 de abril 4454, Oficina 31, Estación Central, Santiago, Chile");
            txtCorreoEmpresa.setText("gerencia@acima.cl");
            txtContactoEmpresa.setText("+56-232107900");
        }
    }//GEN-LAST:event_cmbEmpresaMercaderiaItemStateChanged

    private void btnAgregarProductoMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoMercaderiaActionPerformed
        try {
            int reply;
            do {
                Object[] row = new Object[15];
                DefaultTableModel modeloNuevo = (DefaultTableModel) tblMercaderia.getModel();

                String nombre = JOptionPane.showInputDialog("Ingrese Nombre de Producto");
                String cant = JOptionPane.showInputDialog("Ingrese Cantidad");
                int cantidad = Integer.parseInt(cant);
                String precioStr = JOptionPane.showInputDialog("Ingrese Precio");
                int precio = Integer.parseInt(precioStr);
                String precioFormat = java.text.NumberFormat.getCurrencyInstance().format(precio);

                int calculo = 0;
                calculo = (precio * cantidad);
                String calculoFormat = java.text.NumberFormat.getCurrencyInstance().format(calculo);
                reply = JOptionPane.showConfirmDialog(null, "Confirma Producto", null, JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    row[0] = nombre;
                    row[1] = cant;
                    row[2] = precioFormat.substring(2);
                    row[3] = calculoFormat.substring(2);
                    modeloNuevo.addRow(row);
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese la información de nuevo");
                }
            } while (reply == JOptionPane.NO_OPTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_btnAgregarProductoMercaderiaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tblMercaderia.getModel();
            int SelectedRowIndex = tblMercaderia.getSelectedRow();
            model.removeRow(SelectedRowIndex);
            JOptionPane.showMessageDialog(null, "Producto Removido");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoMercaderia;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInsertarMercaderia;
    private javax.swing.JComboBox<String> cmbComunaMercaderia;
    private javax.swing.JComboBox<String> cmbEmpresaMercaderia;
    private javax.swing.JComboBox<String> cmbRegionMercaderia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane panelFactura1;
    private javax.swing.JPanel panelMercaderia;
    private javax.swing.JTable tblMercaderia;
    private javax.swing.JTextField txtContactoCliente;
    private javax.swing.JTextField txtContactoEmpresa;
    private javax.swing.JTextField txtCorreoEmpresa;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDireccionEmpresa;
    private javax.swing.JTextField txtExtento;
    private javax.swing.JTextField txtFormaPago;
    private javax.swing.JTextField txtGiroCliente;
    private javax.swing.JTextField txtGiroEmpresa;
    private javax.swing.JTextField txtImpuestoAdicional;
    private javax.swing.JTextField txtIvaDebito;
    private javax.swing.JTextField txtMontoNeto;
    private javax.swing.JTextField txtNumeroCotizacion;
    private javax.swing.JTextField txtNumeroFactura;
    public javax.swing.JTextField txtNumeroNotaCompra;
    private javax.swing.JTextField txtOrganizacion;
    private javax.swing.JTextField txtPagos;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JFormattedTextField txtRutCliente;
    private javax.swing.JFormattedTextField txtRutEmpresa;
    private javax.swing.JTextField txtTipoCompra;
    private javax.swing.JTextField txtTipoVenta;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
