
import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author The_S
 */
public class IngresoSalida extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public IngresoSalida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane5 = new javax.swing.JLayeredPane();
        jPanel13 = new javax.swing.JPanel();
        btnIngreso1 = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        lblIngresoSalida = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jLayeredPane5.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLayeredPane5.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLayeredPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        btnIngreso1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnIngreso1.setText("Ingreso de Mercadería");
        btnIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreso1ActionPerformed(evt);
            }
        });
        jPanel13.add(btnIngreso1);

        btnSalida.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSalida.setText("Salida de Mercadería");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel13.add(btnSalida);

        btnSalir1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSalir1.setText("Volver");
        btnSalir1.setToolTipText("");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel13.add(btnSalir1);

        jLayeredPane5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 316, 1256, -1));

        lblIngresoSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuTest.png"))); // NOI18N
        jLayeredPane5.add(lblIngresoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCodigo.setVisible(false);
        jLayeredPane5.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        lblContacto.setText("jLabel1");
        jLayeredPane5.add(lblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        lblFono.setText("jLabel1");
        jLayeredPane5.add(lblFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        SalidasPendientes salidas = new SalidasPendientes();
        salidas.setVisible(true);
        salidas.lblCodigo.setText(lblCodigo.getText());
        salidas.lblContacto.setText(lblContacto.getText());
        salidas.lblFono.setText(lblFono.getText());
        // this.dispose();
        try {
            String query = "Select s.codigoOrdenCompra as 'Codigo de Orden de Compra',\n"
                    + "s.tipoTransporte as 'Transporte',s.netoTransporte as 'Neto',s.ivaTransporte as 'IVA',s.totalTransporte as 'Total',b.nombreBodega as 'Nombre de Bodega',\n"
                    + "s.seccion as 'Sección',bu.codigoBulto as 'Bulto de Salida', s.fechaSalida as 'Fecha de Solicitud',ordenTransporte as 'Orden de Transporte'\n"
                    + "from salida s join bodega b on s.idBodega=b.idBodega\n"
                    + "join bulto bu on s.codigoOrdenCompra = bu.codigoOrdenCompra\n"
                    + "where s.tipoTransporte='Pendiente'\n"
                    + "group by s.codigoOrdenCompra;";
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            salidas.tblSalidasPendientes.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            salidas.cmbSalidasPendientes.removeAllItems();
            String query = "select CONCAT('TRANSPORTE: ',transporte,' - DIRECCIÓN: ',DIRECCIONCARGA,' - COMUNA: ',NomComuna,' - PROVINCIA: ',PROVINCIA,' - REGIÓN: ',NOMREGION) from TRANSPORTE T ;";
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                salidas.cmbSalidasPendientes.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreso1ActionPerformed
//        this.dispose();
        Ingreso ingreso = new Ingreso();
        ingreso.setVisible(true);
        /*
         try {
         String query = "Select idProducto as 'ID producto', SKU, categoria as 'Categoría', nombreProducto as 'Producto', descripcion as 'Descripción' ,\n"
         + "Concat('$',precioVenta )as 'Precio Venta', precioCosto as 'Precio Costo', d.nombreDistribuidor as 'Nombre de Distribuidor', regiones as 'Regiones',\n"
         + "CondicionDespacho as 'Condición de Despacho', diasHabiles as 'Días Hábiles', StatusProducto as 'Estado', stock as 'Stock' \n"
         + "FROM inventario  p join distribuidor d on p.idDistribuidor = d.idDistribuidor;";
         PreparedStatement pst = cn.prepareStatement(query);
         ResultSet rs = pst.executeQuery();
         tblInventario.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (Exception ex) {
         JOptionPane.showMessageDialog(null, ex.getMessage());
         }
         */
        /*
         try {
         String query = "select nombreDistribuidor from distribuidor";
         PreparedStatement pst = cn.prepareStatement(query);
         ResultSet rs = pst.executeQuery();
         while (rs.next()) {
         cmbDistribuidorIngreso.addItem(rs.getString(1));
         }
         } catch (Exception ex) {
         JOptionPane.showMessageDialog(null, ex.getMessage());
         }*/
        try {
            String query = "select nombreBodega,seccion from bodega";
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                ingreso.cmbBodega.addItem(rs.getString(1));
                ingreso.cmbSeccionBodega.addItem(rs.getString(2));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnIngreso1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoSalida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso1;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel13;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblContacto;
    public javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblIngresoSalida;
    // End of variables declaration//GEN-END:variables
}
