
import clases.Conexion;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author The_S
 */
public class Ingreso extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public Ingreso() {
        initComponents();
    }

    //Metodos de Generación de QR
    public static void createQRCode(String qrCodeData, String filePath,
            String charset, Map hintMap, int qrCodeheight, int qrCodewidth)
            throws WriterException, IOException {
        BitMatrix matrix = new MultiFormatWriter().encode(
                new String(qrCodeData.getBytes(charset), charset),
                BarcodeFormat.QR_CODE, qrCodewidth, qrCodeheight, hintMap);
        MatrixToImageWriter.writeToFile(matrix, filePath.substring(filePath
                .lastIndexOf('.') + 1), new File(filePath));
    }

    public static String readQRCode(String filePath, String charset, Map hintMap)
            throws FileNotFoundException, IOException, NotFoundException {
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(
                new BufferedImageLuminanceSource(
                        ImageIO.read(new FileInputStream(filePath)))));
        Result qrCodeResult = new MultiFormatReader().decode(binaryBitmap,
                hintMap);
        return qrCodeResult.getText();
    }

    private static final String ALPHA_NUMERIC_STRING = "0123456789";

    public static String randomAlphaNumeric(int count) {
        StringBuilder builder = new StringBuilder();
        while (count-- != 0) {
            int character = (int) (Math.random() * ALPHA_NUMERIC_STRING.length());
            builder.append(ALPHA_NUMERIC_STRING.charAt(character));
        }
        return builder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane6 = new javax.swing.JLayeredPane();
        jPanel39 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        cmbTransporte = new javax.swing.JComboBox<String>();
        cmbBodega = new javax.swing.JComboBox<String>();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        panelIngresoProducto = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        txtIDproductoIngreso = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        txtStockIngresado = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtSKUIngreso = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtNombreProductoIngreso = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        btnConfirmarInfoProd = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblProductosEnNC = new javax.swing.JTable();
        btnIngresarMercadería = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblPreview = new javax.swing.JLabel();
        cmbSeccionBodega = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtNumeroNotaCompra = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblProductosAIngresar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        txtGuiaDespacho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDistribuidor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnVolver5 = new javax.swing.JButton();
        lblIngresoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel73.setText("Transporte:");

        cmbTransporte.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbTransporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Transporte", "Acima", "Transporte Externo" }));

        cmbBodega.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel74.setText("Bodega:");

        panelIngresoProducto.setVisible(false);
        panelIngresoProducto.setBackground(new java.awt.Color(0, 153, 153));
        panelIngresoProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelIngresoProducto.setEnabled(false);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("ID de Producto:");

        txtIDproductoIngreso.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Stock a Ingresar:");

        txtStockIngresado.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("SKU:");

        txtSKUIngreso.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Nombre de Producto:");

        txtNombreProductoIngreso.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(198, 0, 0));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("*Nota: No toda la información de un producto estará disponible en la nota de compra");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Información del Producto:");

        btnConfirmarInfoProd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnConfirmarInfoProd.setText("1-. Confirmar Información de Producto");
        btnConfirmarInfoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarInfoProdActionPerformed(evt);
            }
        });

        tblProductosEnNC = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblProductosEnNC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID de Producto", "SKU", "Nombre de Producto", "Stock a Ingresar"
            }
        ));
        jScrollPane8.setViewportView(tblProductosEnNC);

        btnIngresarMercadería.setBackground(new java.awt.Color(51, 204, 0));
        btnIngresarMercadería.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnIngresarMercadería.setText("2-. Confirmar Ingreso de Productos");
        btnIngresarMercadería.setToolTipText("");
        btnIngresarMercadería.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIngresarMercadería.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarMercaderíaActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Productos en el Ingreso:");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel75.setText("Código QR generado:");

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelIngresoProductoLayout = new javax.swing.GroupLayout(panelIngresoProducto);
        panelIngresoProducto.setLayout(panelIngresoProductoLayout);
        panelIngresoProductoLayout.setHorizontalGroup(
            panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngresoProductoLayout.createSequentialGroup()
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresoProductoLayout.createSequentialGroup()
                        .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnConfirmarInfoProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel75)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnIngresarMercadería, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIngresoProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel68))
                                .addGap(57, 57, 57)
                                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSKUIngreso)
                                    .addComponent(txtIDproductoIngreso)
                                    .addComponent(txtNombreProductoIngreso)
                                    .addComponent(txtStockIngresado)))
                            .addComponent(jScrollPane8)
                            .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelIngresoProductoLayout.setVerticalGroup(
            panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50)
                .addGap(10, 10, 10)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDproductoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtSKUIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtNombreProductoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtStockIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(panelIngresoProductoLayout.createSequentialGroup()
                        .addGroup(panelIngresoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmarInfoProd)
                            .addComponent(jLabel75))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarMercadería)
                        .addGap(23, 23, 23))))
        );

        cmbSeccionBodega.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel55.setText("Sección de Bodega:");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel59.setText("Código de Nota de Venta:");

        txtNumeroNotaCompra.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNumeroNotaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroNotaCompraKeyPressed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton6.setText("Buscar Nota de Venta - Compra");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tblProductosAIngresar = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblProductosAIngresar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductosAIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosAIngresarMouseClicked(evt);
            }
        });
        tblProductosAIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProductosAIngresarKeyPressed(evt);
            }
        });
        jScrollPane9.setViewportView(tblProductosAIngresar);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("N° de Factura:");

        txtNumFactura.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        txtGuiaDespacho.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Guía de Despacho:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Distribuidor:");

        txtDistribuidor.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistribuidorActionPerformed(evt);
            }
        });
        txtDistribuidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDistribuidorKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Productos Solicitados");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroNotaCompra)
                                    .addComponent(txtDistribuidor)
                                    .addComponent(cmbTransporte, 0, 423, Short.MAX_VALUE)
                                    .addComponent(cmbBodega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumFactura)
                                    .addComponent(txtGuiaDespacho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbSeccionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane9)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelIngresoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel59)
                    .addComponent(txtNumeroNotaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(cmbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(cmbSeccionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuiaDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelIngresoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane10.setViewportView(jPanel14);

        jTabbedPane5.addTab("Formulario de ingreso de mercadería", jScrollPane10);

        btnVolver5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnVolver5.setText("Volver");
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver5)
                .addContainerGap())
        );

        lblIngresoFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuTest.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane6.setLayer(jPanel39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(lblIngresoFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane6)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarInfoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarInfoProdActionPerformed
        try {
            //Agregar los productos a la lista
            int indexs = tblProductosEnNC.getRowCount() + 1;
            Object[] row = new Object[4];
            DefaultTableModel modeloNuevo = (DefaultTableModel) tblProductosEnNC.getModel();
            for (int i = 0; i < indexs; i++) {
                row[0] = txtIDproductoIngreso.getText();
                row[1] = txtSKUIngreso.getText();
                row[2] = txtNombreProductoIngreso.getText();
                row[3] = txtStockIngresado.getText();
                modeloNuevo.addRow(row);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarInfoProdActionPerformed

    private void btnIngresarMercaderíaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarMercaderíaActionPerformed
        try {
            int idBodega = 0;
            String query = "select * from bodega where nombreBodega = ?";
            PreparedStatement pst3 = cn.prepareStatement(query);
            pst3.setString(1, cmbBodega.getSelectedItem().toString());
            ResultSet rs3 = pst3.executeQuery();
            while (rs3.next()) {
                idBodega = rs3.getInt("idBodega");
            }
            //Metodo para Escoger la ruta donde se guardara el reporte
            String ruta = "";
            String nombre = "Acima Group - " + idBodega + randomAlphaNumeric(4);
            JFileChooser dlg = new JFileChooser();
            dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            int option = dlg.showOpenDialog(this);

            if (option == JFileChooser.APPROVE_OPTION) {
                File f = dlg.getSelectedFile();
                ruta = f.toString() + "\\" + nombre + ".png";
            }
            String qrCodeData;
            qrCodeData = nombre;
            String charset = "UTF-8"; // or "ISO-8859-1"
            Map hintMap = new HashMap();
            hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            try {
                createQRCode(qrCodeData, ruta, charset, hintMap, 800, 800);
            } catch (WriterException | IOException ex) {
                Logger.getLogger(Login.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Se ha creado Código QR con éxito");
            try {
                System.out.println("Datos obtenidos de Código QR: "
                        + readQRCode(ruta, charset, hintMap));
            } catch (IOException | NotFoundException ex) {
                Logger.getLogger(Login.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(
                    null, "Se ha Generado un Código QR con la siguiente información: " + qrCodeData);
            //Cargar un preview del Código
            try {
                File FileToRead = new File(ruta);
                Image Picture = ImageIO.read(FileToRead);
                BufferedImage img = (BufferedImage) Picture;
                Image dimg = img.getScaledInstance(lblPreview.getWidth(), lblPreview.getHeight(),
                        Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(dimg);
                lblPreview.setIcon(icon);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            try {
                DefaultTableModel model = (DefaultTableModel) tblProductosEnNC.getModel();
                int rowcount = tblProductosEnNC.getRowCount();
                for (int i = 0; i < rowcount; i++) {
                    String query3 = "INSERT INTO ingreso(`numeroCotizacion`, `nombreDistribuidor`,numeroFactura,guiaDespachoProveedor, "
                            + "`tipoTransporte`, `idBodega`,`IDProducto`,`SKU`,"
                            + "`codigoGeneradoQR`,`StockIngresado`,`tipoIngreso`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pst2 = cn.prepareStatement(query3);
                    pst2.setString(1, txtNumeroNotaCompra.getText());
                    pst2.setString(2, txtDistribuidor.getText());
                    pst2.setString(3, txtNumFactura.getText());
                    pst2.setString(4, txtGuiaDespacho.getText());
                    pst2.setString(5, cmbTransporte.getSelectedItem().toString());
                    pst2.setInt(6, cmbBodega.getSelectedIndex());
                    pst2.setString(7, model.getValueAt(i, 0).toString());
                    pst2.setString(8, model.getValueAt(i, 1).toString());
                    pst2.setString(9, qrCodeData);
                    pst2.setString(10, model.getValueAt(i, 3).toString());
                    pst2.setString(11, "Ingreso realizado por 'Ingreso de Mercadería'");
                    int up = pst2.executeUpdate();
                    String queryINV = "UPDATE INVENTARIO SET STOCK = stock + ? WHERE IDPRODUCTO = ?";
                    PreparedStatement pstINV = cn.prepareStatement(queryINV);
                    pstINV.setInt(1, Integer.parseInt(tblProductosEnNC.getValueAt(i, 3).toString()));
                    pstINV.setString(2, tblProductosEnNC.getValueAt(i, 1).toString());
                    int upINV = pstINV.executeUpdate();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR EN :" + ex.getMessage());
            }
        } catch (NumberFormatException | SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "ERROR EN :" + ex.getMessage());
        }
        try {
            // create the java mysql update preparedstatement
            String query = "update abastecimiento set estado = 'Cotización Validada' where numerocotizacion = ?";
            PreparedStatement preparedStmt = cn.prepareStatement(query);
            preparedStmt.setString(1, txtNumeroNotaCompra.getText());
            // execute the java preparedstatement
            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cotización validada: " + txtNumeroNotaCompra.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + ex.getMessage());
        }

        int index_borrar = tblProductosEnNC.getRowCount();
        DefaultTableModel modelo_paso = (DefaultTableModel) tblProductosEnNC.getModel();
        for (int i = index_borrar - 1; i >= 0; i--) {
            modelo_paso.removeRow(i);
        }

        txtNumeroNotaCompra.setText("");
        txtIDproductoIngreso.setText("");
        txtSKUIngreso.setText("");
        txtNombreProductoIngreso.setText("");
        txtStockIngresado.setText("");
    }//GEN-LAST:event_btnIngresarMercaderíaActionPerformed

    private void txtNumeroNotaCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroNotaCompraKeyPressed

    }//GEN-LAST:event_txtNumeroNotaCompraKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String query = "SELECT SKU, CODIGOPRODUCTO AS 'CODIGO DE PRODUCTO', CATEGORIA AS 'CATEGORÍA', NOMBRE AS 'NOMBRE DE PRODUCTO',CANTIDAD AS 'CANTIDAD',\n"
                    + "PRECIOUNITARIO AS 'PRECIOUNITARIO',PRECIOTOTALNETO AS 'PRECIO TOTAL NETO'\n"
                    + "FROM detalle_abastecimiento da join abastecimiento a on da.numeroCotizacion = a.numeroCotizacion\n"
                    + "WHERE a.codigoOrdenCompra = ?";
            String param = txtNumeroNotaCompra.getText();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            tblProductosAIngresar.setModel(DbUtils.resultSetToTableModel(rs));
            while (rs.next()) {
                txtIDproductoIngreso.setText("");
                txtSKUIngreso.setText(rs.getString(""));
                txtNombreProductoIngreso.setText(rs.getString("Nombredelproducto"));
                txtStockIngresado.setText(rs.getString("cantidadProducto"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error:" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblProductosAIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosAIngresarMouseClicked
        try {
            panelIngresoProducto.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) tblProductosAIngresar.getModel();
            int selectedRow = tblProductosAIngresar.getSelectedRow();
            String query = "Select * FROM inventario where idProducto = ?";
            String param = model.getValueAt(selectedRow, 1).toString();
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, param);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                txtIDproductoIngreso.setText(rs.getString("IDPRODUCTO"));
                txtSKUIngreso.setText(rs.getString("SKU"));
                txtNombreProductoIngreso.setText(rs.getString("Nombreproducto"));
                txtStockIngresado.setText("");
            }
            JOptionPane.showMessageDialog(null, "Ingrese la información del producto a ingresar en el formulario de abajo:");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblProductosAIngresarMouseClicked

    private void tblProductosAIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosAIngresarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosAIngresarKeyPressed

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver5ActionPerformed

    private void txtDistribuidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDistribuidorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistribuidorKeyPressed

    private void txtDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistribuidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistribuidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarInfoProd;
    private javax.swing.JButton btnIngresarMercadería;
    private javax.swing.JButton btnVolver5;
    public javax.swing.JComboBox<String> cmbBodega;
    public javax.swing.JComboBox cmbSeccionBodega;
    public javax.swing.JComboBox<String> cmbTransporte;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel lblIngresoFrame;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JPanel panelIngresoProducto;
    private javax.swing.JTable tblProductosAIngresar;
    private javax.swing.JTable tblProductosEnNC;
    public javax.swing.JTextField txtDistribuidor;
    private javax.swing.JTextField txtGuiaDespacho;
    private javax.swing.JTextField txtIDproductoIngreso;
    private javax.swing.JTextField txtNombreProductoIngreso;
    private javax.swing.JTextField txtNumFactura;
    public javax.swing.JTextField txtNumeroNotaCompra;
    private javax.swing.JTextField txtSKUIngreso;
    private javax.swing.JTextField txtStockIngresado;
    // End of variables declaration//GEN-END:variables
}
