
import clases.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author The_S
 */
public class Salida extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conecta();

    public Salida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bultos = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel20 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        txtNumeroBultos = new javax.swing.JTextField();
        jScrollPane26 = new javax.swing.JScrollPane();
        tblProdBultos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane28 = new javax.swing.JScrollPane();
        tblProdsAgregadosBulto = new javax.swing.JTable();
        jLabel157 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtAlto = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        jLabel156 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLayeredPane12 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        btnSalida1 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        cmbBodegaSalida = new javax.swing.JComboBox();
        jScrollPane27 = new javax.swing.JScrollPane();
        tblResumenBultos = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        txtCodigoOTSalida = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        btnBuscarOTSalida = new javax.swing.JButton();
        panelGD = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        cmbTipoDespacho = new javax.swing.JComboBox();
        jLabel70 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        jLabel131 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jPanel23 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jTabbedPane15 = new javax.swing.JTabbedPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblMPSalida = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        txtImpuestoEspecificoSalida = new javax.swing.JTextField();
        txtIVAOCSalida = new javax.swing.JTextField();
        txtSubtotalOCSalida = new javax.swing.JTextField();
        txtCargosOCSalida = new javax.swing.JTextField();
        txtDCTOOCSalida = new javax.swing.JTextField();
        txtNetoOCSalida = new javax.swing.JTextField();
        txtTotalOCSalida = new javax.swing.JTextField();
        txtRutCompradorSalida = new javax.swing.JTextField();
        txtTelefonoCompradorSalida = new javax.swing.JTextField();
        txtUnidadCompraClienteSalida = new javax.swing.JTextField();
        txtNombreDemandanteOCSalida = new javax.swing.JTextField();
        txtFechaEnvioOcSalida = new javax.swing.JTextField();
        txtProveedorOCSalida = new javax.swing.JTextField();
        txtNombreOrdenCompraSalida = new javax.swing.JTextField();
        txtFechaEntregaProductoOCSalida = new javax.swing.JTextField();
        txtDireccionesDespachoOCSalida = new javax.swing.JTextField();
        txtContactoOCSalida = new javax.swing.JTextField();
        txtDescripcionOCSalida = new javax.swing.JTextField();
        jLabel155 = new javax.swing.JLabel();
        txtObservacionesGuiaDespacho = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver2 = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        lblFondoSalida = new javax.swing.JLabel();

        bultos.setMinimumSize(new java.awt.Dimension(1280, 740));
        bultos.setResizable(false);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel83.setText("Número de Bulto:");

        txtNumeroBultos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNumeroBultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroBultosActionPerformed(evt);
            }
        });

        tblProdBultos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdBultos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdBultosMouseClicked(evt);
            }
        });
        jScrollPane26.setViewportView(tblProdBultos);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Agregar a bulto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblProdsAgregadosBulto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Producto", "Nombre de Producto", "Cantidad", "Moneda", "Precio Unitario", "Descuento", "Cargos", "Valor Total", "Largo", "Ancho", "Alto", "Peso (KG)", "Número de Bultos"
            }
        ));
        jScrollPane28.setViewportView(tblProdsAgregadosBulto);

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel157.setText("Resumen de Bulto:");

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setText("Confirmar y volver");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel153.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel153.setText("Ancho:");

        jLabel154.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel154.setText("Peso:");

        jLabel152.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel152.setText("Largo:");

        jLabel89.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel89.setText("Alto:");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel84.setText("Cantidad del producto en bulto:");

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQty.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQtyInputMethodTextChanged(evt);
            }
        });
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        txtAlto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtLargo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtPeso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtAncho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel156.setText("KG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel154)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel84)
                            .addComponent(jLabel89)
                            .addComponent(jLabel152)
                            .addComponent(jLabel153))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtAlto)
                            .addComponent(txtLargo)
                            .addComponent(txtAncho)
                            .addComponent(txtPeso))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel156)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel152)
                    .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel153)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel154)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel156))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Stock en Inventario:");

        lblStock.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblStock.setText("0");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane28)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblStock))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addComponent(jLabel83)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumeroBultos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(113, 113, 113)))
                    .addComponent(jLabel157)
                    .addComponent(jButton3)
                    .addComponent(jButton13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(txtNumeroBultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblStock))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel157)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel20);

        jInternalFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1240, 520));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuTest.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 710));

        javax.swing.GroupLayout bultosLayout = new javax.swing.GroupLayout(bultos.getContentPane());
        bultos.getContentPane().setLayout(bultosLayout);
        bultosLayout.setHorizontalGroup(
            bultosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        bultosLayout.setVerticalGroup(
            bultosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalida1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSalida1.setText("Salida de Mercadería");
        btnSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalida1ActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel69.setText("Bodega:");

        cmbBodegaSalida.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        tblResumenBultos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane27.setViewportView(tblResumenBultos);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBodegaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbBodegaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69))
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigoOTSalida.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel51.setText("Código de Orden de Compra:");

        btnBuscarOTSalida.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBuscarOTSalida.setText("Buscar Nota");
        btnBuscarOTSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarOTSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoOTSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBuscarOTSalida)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txtCodigoOTSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarOTSalida))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelGD.setEnabled(false);

        jLabel147.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel147.setText("Tipo de Traslado:");

        cmbTipoDespacho.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbTipoDespacho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Traslado", "Operación Constituye Venta", "Ventas por Efectuar", "Consignaciones", "Entrega Gratuita", "Traslados Internos", "Otros Traslados - No Venta", "Guía de Devolución" }));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel70.setText("Número de Guía de Despacho:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Número de factura:");

        txtNumeroFactura.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        javax.swing.GroupLayout panelGDLayout = new javax.swing.GroupLayout(panelGD);
        panelGD.setLayout(panelGDLayout);
        panelGDLayout.setHorizontalGroup(
            panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel147)
                    .addComponent(jLabel70)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipoDespacho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(txtNumeroFactura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGDLayout.setVerticalGroup(
            panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel147))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel131.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel131.setText("Resumen de Bultos:");

        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel122.setText("Proveedor:");

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel125.setText("Información de la empresa:");

        jLabel130.setText("Rut de Comprador:");

        jLabel159.setText("Demandante:");

        jLabel166.setText("Fecha de Envio OC:");

        jLabel168.setText("Teléfono:");

        jLabel169.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel169.setText("Información de Demandante:");

        jLabel170.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel170.setText("Información de Nota:");

        jLabel171.setText("Nombre de Orden de Compra:");

        jLabel172.setText("Fecha de Aceptación:");

        jLabel173.setText("Direcciones de Despacho:");

        jLabel178.setText("Contacto OC:");

        jLabel180.setText("Descripción de Orden:");

        jLabel181.setText("Unidad de Compra:");

        tblMPSalida = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int celIndex){
                return false;
            }
        };
        tblMPSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código / ID Licitación CM", "Producto", "Cantidad", "Especificación de Comprador", "Especificación de Proveedor", "Precio Unitario", "Descuento", "Cargos", "Valor Total"
            }
        ));
        jScrollPane14.setViewportView(tblMPSalida);

        jTabbedPane15.addTab("Información de Productos", jScrollPane14);

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel182.setText("Neto:");

        jLabel183.setText("Dcto:");

        jLabel184.setText("Cargos:");

        jLabel185.setText("Subtotal:");

        jLabel186.setText("19% IVA:");

        jLabel187.setText("Impuesto Especifico:");

        jLabel188.setText("Total:");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel187)
                    .addComponent(jLabel186)
                    .addComponent(jLabel185)
                    .addComponent(jLabel184)
                    .addComponent(jLabel183)
                    .addComponent(jLabel182)
                    .addComponent(jLabel188))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtImpuestoEspecificoSalida)
                    .addComponent(txtIVAOCSalida)
                    .addComponent(txtSubtotalOCSalida)
                    .addComponent(txtCargosOCSalida)
                    .addComponent(txtDCTOOCSalida)
                    .addComponent(txtNetoOCSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(txtTotalOCSalida))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel182)
                    .addComponent(txtNetoOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel183)
                    .addComponent(txtDCTOOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel184)
                    .addComponent(txtCargosOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel185)
                    .addComponent(txtSubtotalOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel186)
                    .addComponent(txtIVAOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel187)
                    .addComponent(txtImpuestoEspecificoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel188)
                    .addComponent(txtTotalOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane15.addTab("Totales", jPanel24);

        txtDireccionesDespachoOCSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionesDespachoOCSalidaActionPerformed(evt);
            }
        });

        jLabel155.setText("Observaciones:");

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton12.setText("Ingresar productos a bultos");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel169)
                    .addComponent(jButton12)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel155)
                                .addGap(91, 91, 91)
                                .addComponent(txtObservacionesGuiaDespacho))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel171)
                                    .addComponent(jLabel173)
                                    .addComponent(jLabel180))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaEntregaProductoOCSalida)
                                    .addComponent(txtNombreOrdenCompraSalida)
                                    .addComponent(txtDireccionesDespachoOCSalida)
                                    .addComponent(txtDescripcionOCSalida)))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel172)
                                    .addComponent(jLabel170)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel122)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProveedorOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel178)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContactoOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel168)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefonoCompradorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel130)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRutCompradorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel181))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel159))))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel125)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel166)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUnidadCompraClienteSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addComponent(txtFechaEnvioOcSalida)
                            .addComponent(txtNombreDemandanteOCSalida))))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel169)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRutCompradorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel130)
                            .addComponent(jLabel159))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel168)
                            .addComponent(txtTelefonoCompradorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel125)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProveedorOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel122))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel170))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(txtNombreDemandanteOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadCompraClienteSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel181))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaEnvioOcSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel166))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel171)
                    .addComponent(txtNombreOrdenCompraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel178)
                    .addComponent(txtContactoOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel172)
                    .addComponent(txtFechaEntregaProductoOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionesDespachoOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel173))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionOCSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel180))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacionesGuiaDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel155))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap())
        );

        jScrollPane23.setViewportView(jPanel23);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel54.setText("Resumen / Información de Nota de Venta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Datos de facturación:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel131)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 1304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalida1)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel54)
                                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel131)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalida1)
                .addGap(115, 115, 115))
        );

        jScrollPane6.setViewportView(jPanel10);

        jTabbedPane4.addTab("Ingresar formulario Salida", jScrollPane6);

        btnVolver2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        lblCodigo.setVisible(false);

        lblContacto.setVisible(false);

        lblFono.setVisible(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblFono)
                        .addGap(37, 37, 37)
                        .addComponent(lblContacto)
                        .addGap(148, 148, 148)
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver2)
                    .addComponent(lblCodigo)
                    .addComponent(lblContacto)
                    .addComponent(lblFono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblFondoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuTest.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane12Layout = new javax.swing.GroupLayout(jLayeredPane12);
        jLayeredPane12.setLayout(jLayeredPane12Layout);
        jLayeredPane12Layout.setHorizontalGroup(
            jLayeredPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane12Layout.setVerticalGroup(
            jLayeredPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane12.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(lblFondoSalida, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane12)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalida1ActionPerformed
        if (cmbTipoDespacho.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de despacho");
        } else {
            try {
                try {

                    int idBodega = 0;
                    String queryBodega = "select idBodega from bodega where nombreBodega=?";
                    String paramBodega = cmbBodegaSalida.getSelectedItem().toString();
                    PreparedStatement pstBodega = cn.prepareStatement(queryBodega);
                    pstBodega.setString(1, paramBodega);
                    ResultSet rsBodega = pstBodega.executeQuery();
                    while (rsBodega.next()) {
                        idBodega = rsBodega.getInt("idBodega");
                    }
                    int transporte = 0;
                    TableModel modelo = tblMPSalida.getModel();
                    int cantidadRows = tblMPSalida.getRowCount();
                    try {
                        String query = "insert into salida (`codigoOrdenCompra`,`idBodega`,numFactura) values(?,?,?)";
                        PreparedStatement insert = cn.prepareStatement(query);
                        insert.setString(1, txtCodigoOTSalida.getText());
                        insert.setInt(2, idBodega);
                        insert.setInt(3, Integer.parseInt(txtNumeroFactura.getText()));
                        int up = insert.executeUpdate();
                        System.out.println(cantidadRows);
                        for (int i = 0; i < cantidadRows; i++) {
                            String queryDetalle = "INSERT INTO `acimabasededatos`.`detallesalida` (`codigoOrdenCompra`,`idProducto`,`stockrestado`) VALUES(?,?,?);";
                            PreparedStatement pstDetalle = cn.prepareStatement(queryDetalle);
                            pstDetalle.setString(1, txtCodigoOTSalida.getText());
                            pstDetalle.setString(2, tblMPSalida.getValueAt(i, 0).toString());
                            pstDetalle.setInt(3, Integer.parseInt(tblMPSalida.getValueAt(i, 2).toString()));
                            int upDetalle = pstDetalle.executeUpdate();
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Error en salida / detalle:" + ex.getMessage());
                    }

                    try {
                        int rowsBultos = tblResumenBultos.getRowCount();
                        for (int i = 0; i < rowsBultos; i++) {

                            String queryDetalle = "INSERT INTO `acimabasededatos`.`bulto` (`codigobulto`,`codigoOrdenCompra`,`codigoProducto`,`cantidad`,`largo`,`ancho`,`alto`,`peso`) VALUES(?,?,?,?,?,?,?,?);";
                            PreparedStatement pstDetalle = cn.prepareStatement(queryDetalle);
                            pstDetalle.setString(1, tblResumenBultos.getValueAt(i, 12).toString());
                            pstDetalle.setString(2, txtCodigoOTSalida.getText());
                            pstDetalle.setString(3, tblResumenBultos.getValueAt(i, 0).toString());
                            pstDetalle.setInt(4, Integer.parseInt(tblResumenBultos.getValueAt(i, 2).toString()));
                            pstDetalle.setString(5, tblResumenBultos.getValueAt(i, 8).toString());
                            pstDetalle.setString(6, tblResumenBultos.getValueAt(i, 9).toString());
                            pstDetalle.setString(7, tblResumenBultos.getValueAt(i, 10).toString());
                            pstDetalle.setString(8, tblResumenBultos.getValueAt(i, 11).toString());
                            int upDetalle = pstDetalle.executeUpdate();

                            //Realizar la resta de productos
                            int stock = Integer.parseInt(tblResumenBultos.getValueAt(i, 2).toString());
                            String query1 = "UPDATE inventario SET stock = stock - ?  WHERE idProducto=?";
                            PreparedStatement pst = cn.prepareStatement(query1);
                            pst.setInt(1, stock);
                            pst.setString(2, tblResumenBultos.getValueAt(i, 0).toString());
                            int upd = pst.executeUpdate();

                        }
                        int resumen = tblResumenBultos.getRowCount();
                        for (int i = 0; i < resumen; i++) {
                            int stock2 = Integer.parseInt(tblResumenBultos.getValueAt(i, 2).toString());
                            String que2ry2 = "UPDATE detalleordentrabajo SET cantidad = cantidad-?  WHERE idorden=?";
                            PreparedStatement pst2 = cn.prepareStatement(que2ry2);
                            pst2.setInt(1, stock2);
                            pst2.setString(2, txtCodigoOTSalida.getText());
                            int upd2 = pst2.executeUpdate();
                        }
                    } catch (Exception ex) {
                        // JOptionPane.showMessageDialog(null, "Error en bulto:" + ex.getMessage());
                    }
                } catch (SQLException | NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Error:" + ex.getMessage());
                }

                //INSERTAR EN BASE DE DATOS
                try {
                    TableModel modelo = tblMPSalida.getModel();
                    int selectedRows = tblMPSalida.getRowCount();
                    String query = "INSERT INTO guiaDespacho(`codigoOrden`,`tipoTraslado`,`observaciones`,"
                            + "`contacto`,`fono`,`direcciondespacho`) "
                            + "VALUES (?,?,?,?,?,?);";
                    for (int i = 0; i <= selectedRows; i++) {
                        PreparedStatement pst = cn.prepareStatement(query);
                        pst.setString(1, txtCodigoOTSalida.getText());
                        pst.setString(2, cmbTipoDespacho.getSelectedItem().toString());
                        pst.setString(3, txtObservacionesGuiaDespacho.getText());
                        pst.setString(4, lblContacto.getText());
                        pst.setString(5, lblFono.getText());
                        pst.setString(6, txtDireccionesDespachoOCSalida.getText());
                        int up = pst.executeUpdate();
                    }
                } catch (SQLException | NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }

                DefaultTableModel dm1 = (DefaultTableModel) tblMPSalida.getModel();
                int rowCount1 = dm1.getRowCount();
                //Remove rows one by one from the end of the table
                for (int i = rowCount1 - 1; i >= 0; i--) {
                    dm1.removeRow(i);
                }

                DefaultTableModel dm2 = (DefaultTableModel) tblResumenBultos.getModel();
                int rowCount2 = dm2.getRowCount();
                //Remove rows one by one from the end of the table
                for (int i = rowCount2 - 1; i >= 0; i--) {
                    dm2.removeRow(i);
                }

                JOptionPane.showMessageDialog(null, "Se ha ingresado formulario de Salida");
                this.dispose();
                SalidasPendientes salidas = new SalidasPendientes();
                try {
                    String query = "Select s.codigoOrdenCompra as 'Codigo de Orden de Compra',\n"
                            + "s.tipoTransporte as 'Transporte',s.netoTransporte as 'Neto',s.ivaTransporte as 'IVA',s.totalTransporte as 'Total',b.nombreBodega as 'Nombre de Bodega',\n"
                            + "s.seccion as 'Sección',bu.codigoBulto as 'Bulto de Salida', s.fechaSalida as 'Fecha de Solicitud',ordenTransporte as 'Orden de Transporte'\n"
                            + "from salida s join bodega b on s.idBodega=b.idBodega\n"
                            + "join bulto bu on s.codigoOrdenCompra = bu.codigoOrdenCompra\n"
                            + "where s.tipoTransporte='Pendiente'\n"
                            + "group by s.codigoOrdenCompra;";
                    PreparedStatement pst = cn.prepareStatement(query);
                    ResultSet rs = pst.executeQuery();
                    salidas.tblSalidasPendientes.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                try {
                    String query = "select transporte from transporte";
                    PreparedStatement pst = cn.prepareStatement(query);
                    ResultSet rs = pst.executeQuery();
                    while (rs.next()) {
                        salidas.cmbSalidasPendientes.addItem(rs.getString(1));
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }

                txtProveedorOCSalida.setText("");
                txtRutCompradorSalida.setText("");
                txtTelefonoCompradorSalida.setText("");
                txtNombreDemandanteOCSalida.setText("");
                txtUnidadCompraClienteSalida.setText("");
                txtFechaEnvioOcSalida.setText("");
                txtNombreOrdenCompraSalida.setText("");
                txtFechaEntregaProductoOCSalida.setText("");
                txtDireccionesDespachoOCSalida.setText("");
                txtContactoOCSalida.setText("");
                txtCargosOCSalida.setText("");
                txtNetoOCSalida.setText("");
                txtDCTOOCSalida.setText("");
                txtSubtotalOCSalida.setText("");
                txtIVAOCSalida.setText("");
                txtImpuestoEspecificoSalida.setText("");
                txtTotalOCSalida.setText("");
                jTextField2.setText("");

                //ingresoSalidaFrame.setVisible(false);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ocurrió un error en la operación: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnSalida1ActionPerformed

    private void btnBuscarOTSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarOTSalidaActionPerformed
        try {
            String tipoOrden = "";
            //  int seleccion = Integer.parseInt(model.getValueAt(index, 0).toString());
            String query = "SELECT * from ordenTrabajo where codigoOrdenCompra = ?;";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, txtCodigoOTSalida.getText());
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                txtProveedorOCSalida.setText(rs.getString("nombre_proveedor"));
                txtRutCompradorSalida.setText(rs.getString("rutCliente"));
                txtTelefonoCompradorSalida.setText(rs.getString("telefono"));
                txtNombreDemandanteOCSalida.setText(rs.getString("demandante"));
                txtUnidadCompraClienteSalida.setText(rs.getString("unidadcompra"));
                txtFechaEnvioOcSalida.setText(rs.getString("fechaenviooc"));
                txtNombreOrdenCompraSalida.setText(rs.getString("nombreordencompra"));
                txtFechaEntregaProductoOCSalida.setText(rs.getString("fechaAceptacion"));
                txtDireccionesDespachoOCSalida.setText(rs.getString("direccionesdespacho"));
                txtContactoOCSalida.setText(rs.getString("contactoOC"));
                txtCargosOCSalida.setText(rs.getString("cargos"));
                txtNetoOCSalida.setText(rs.getString("neto"));
                txtDCTOOCSalida.setText(rs.getString("dcto"));
                txtSubtotalOCSalida.setText(rs.getString("subtotal"));
                txtIVAOCSalida.setText(rs.getString("iva"));
                txtImpuestoEspecificoSalida.setText(rs.getString("impuestoEspecifico"));
                txtTotalOCSalida.setText(rs.getString("total"));
            }
            String queryProducto = "Select doc.codigoProducto as 'Código de Producto',\n"
                    + "SUBSTRING_INDEX(doc.nombreProducto, ')', -1) as 'Nombre de Producto',doc.cantidad as 'Cantidad',\n"
                    + "oc.especificacionComprador as 'Especificación de Comprador',oc.especificacionProveedor as 'Especificación de Proveedor',\n"
                    + "oc.moneda,doc.precioUnitario as 'Precio Unitario', doc.descuento as 'Descuento',\n"
                    + "doc.cargos as 'Cargos', doc.valorTotal as 'Valor Total' from detalleordentrabajo doc\n"
                    + "join ordentrabajo oc on doc.codigoordencompra = oc.codigoordencompra\n"
                    + "where oc.codigoOrdenCompra = ?;";
            PreparedStatement pstProd = cn.prepareStatement(queryProducto);
            pstProd.setString(1, txtCodigoOTSalida.getText());
            ResultSet rsProd = pstProd.executeQuery();
            tblMPSalida.setModel(DbUtils.resultSetToTableModel(rsProd));
            System.out.println("La consulta fue realizada con éxito");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btnBuscarOTSalidaActionPerformed

    private void txtDireccionesDespachoOCSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionesDespachoOCSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionesDespachoOCSalidaActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            DefaultTableModel modeloSalida = (DefaultTableModel) tblMPSalida.getModel();
            tblProdBultos.setModel(modeloSalida);
            bultos.setVisible(true);

            String queryProducto = "Select Max(idBulto)+1 from bulto";
            PreparedStatement pstProd = cn.prepareStatement(queryProducto);

            ResultSet rsProd = pstProd.executeQuery();
            if (rsProd.next()) {
                txtNumeroBultos.setText(Integer.toString(rsProd.getInt(1)));
            }
            System.out.println("La consulta fue realizada con éxito");
        } catch (SQLException ex) {
            Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void txtNumeroBultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroBultosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroBultosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (txtNumeroBultos.getText() != null) {
                if (Integer.parseInt(lblStock.getText()) < Integer.parseInt(txtQty.getText())) {
                    JOptionPane.showMessageDialog(null, "El stock solicitado es mayor al que se encuentra en inventario - STOCK: " + lblStock.getText());
                    txtQty.setText("");
                } else {
                    TableModel cotizacion = tblProdBultos.getModel();
                    int indexs[] = tblProdBultos.getSelectedRows();
                    Object[] row = new Object[14];
                    DefaultTableModel modeloNuevo = (DefaultTableModel) tblProdsAgregadosBulto.getModel();
                    TableModel modelo = tblProdBultos.getModel();
                    int selectedRows[] = tblProdBultos.getSelectedRows();

                    int indice = 0;
                    indice = tblProdBultos.getSelectedRow();

                    int cantidadInicial = 0;
                    cantidadInicial = Integer.parseInt(tblProdBultos.getValueAt(indice, 2).toString());
                    System.out.println(cantidadInicial);

                    for (int i = 0; i <= indexs.length; i++) {
                        System.out.println("Cantidad Inicial: " + cantidadInicial);
                        int cantidad = Integer.parseInt(txtQty.getText());
                        System.out.println("Cantidad solicitada: " + cantidad);
                        if (cantidad <= cantidadInicial) {
                            row[0] = cotizacion.getValueAt(indexs[i], 0);
                            row[1] = cotizacion.getValueAt(indexs[i], 1);
                            row[2] = cantidad;
                            row[3] = cotizacion.getValueAt(indexs[i], 3);
                            row[4] = cotizacion.getValueAt(indexs[i], 4);
                            row[5] = cotizacion.getValueAt(indexs[i], 5);
                            row[6] = cotizacion.getValueAt(indexs[i], 6);
                            row[7] = cotizacion.getValueAt(indexs[i], 7);
                            row[8] = txtLargo.getText();
                            row[9] = txtAncho.getText();
                            row[10] = txtAlto.getText();
                            row[11] = txtPeso.getText();
                            row[12] = txtNumeroBultos.getText();
                            modeloNuevo.addRow(row);
                            modelo.setValueAt((cantidadInicial - cantidad), indice, 2);

                            int resp = JOptionPane.showConfirmDialog(null, "¿Desea añadir mas productos al bulto?\n"
                                    + "", "", JOptionPane.YES_NO_OPTION);
                            if (resp == 0) {
                                JOptionPane.showMessageDialog(null, "Se añadirán más productos al mismo bulto");
                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese nuevo número de bulto");
                                txtNumeroBultos.setText("");

                            }
                        } else {
                            System.out.println("la cantidad debe ser menor");
                            cantidadInicial = 0;
                            JOptionPane.showMessageDialog(null, "La cantidad debe ser menor o igual");
                        }
                    }
                }
                String queryProducto = "Select Max(idBulto)+1 from bulto";
                PreparedStatement pstProd = cn.prepareStatement(queryProducto);

                ResultSet rsProd = pstProd.executeQuery();
                if (rsProd.next()) {
                    txtNumeroBultos.setText(Integer.toString(rsProd.getInt(1)));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese productos al siguiente bulto o de lo contrario, continúe con la operación de salidas");
            }
        } catch (Exception ex) {
            // JOptionPane.showMessageDialog(null, "Ha ocurrido un error " + ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblProdsAgregadosBulto.getModel();
        tblResumenBultos.setModel(modelo);
        bultos.dispose();
        tblProdBultos.removeAll();
        tblProdsAgregadosBulto.removeAll();
        this.setVisible(true);
        this.setTitle("Salida");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtQtyInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtyInputMethodTextChanged

    }//GEN-LAST:event_txtQtyInputMethodTextChanged

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased

    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed

    }//GEN-LAST:event_txtQtyKeyPressed

    private void tblProdBultosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdBultosMouseClicked
        int stock = 0;
        try {
            String query = "SELECT stock FROM inventario where idProducto = ?";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, tblProdBultos.getValueAt(tblProdBultos.getSelectedRow(), 0).toString());
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                stock = rs.getInt("stock");
            }
            lblStock.setText(Integer.toString(stock));
        } catch (SQLException ex) {
            Logger.getLogger(Salida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblProdBultosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarOTSalida;
    private javax.swing.JButton btnSalida1;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JFrame bultos;
    public javax.swing.JComboBox cmbBodegaSalida;
    private javax.swing.JComboBox cmbTipoDespacho;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLayeredPane jLayeredPane12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane15;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblFondoSalida;
    public javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblStock;
    private javax.swing.JPanel panelGD;
    private javax.swing.JTable tblMPSalida;
    private javax.swing.JTable tblProdBultos;
    private javax.swing.JTable tblProdsAgregadosBulto;
    private javax.swing.JTable tblResumenBultos;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCargosOCSalida;
    public javax.swing.JTextField txtCodigoOTSalida;
    private javax.swing.JTextField txtContactoOCSalida;
    private javax.swing.JTextField txtDCTOOCSalida;
    private javax.swing.JTextField txtDescripcionOCSalida;
    private javax.swing.JTextField txtDireccionesDespachoOCSalida;
    private javax.swing.JTextField txtFechaEntregaProductoOCSalida;
    private javax.swing.JTextField txtFechaEnvioOcSalida;
    private javax.swing.JTextField txtIVAOCSalida;
    private javax.swing.JTextField txtImpuestoEspecificoSalida;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtNetoOCSalida;
    private javax.swing.JTextField txtNombreDemandanteOCSalida;
    private javax.swing.JTextField txtNombreOrdenCompraSalida;
    private javax.swing.JTextField txtNumeroBultos;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtObservacionesGuiaDespacho;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtProveedorOCSalida;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRutCompradorSalida;
    private javax.swing.JTextField txtSubtotalOCSalida;
    private javax.swing.JTextField txtTelefonoCompradorSalida;
    private javax.swing.JTextField txtTotalOCSalida;
    private javax.swing.JTextField txtUnidadCompraClienteSalida;
    // End of variables declaration//GEN-END:variables
}
